spring:
  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/
      api-key: sk-35d252365b344f91b2621c9ff9c91b92
      chat:
        options:
          model: qwen-plus-2025-07-28
          temperature: 0.7
      embedding:
        options:
          model: text-embedding-v3
          dimensions: 1024
    mcp:
      client:
        sse:
          connections:
            server1:
              url: https://mcp.api-inference.modelscope.net
              sse-endpoint: 129378b6ba6b4a/sse

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  application:
    name: art-creation
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/newidea
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
# MyBatis-Plus ??
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: AUTO

server:
  port: 8080

my:
  reg_score: 20

